services:
    # Container 1
    todo-app:
        # Image dùng để build container 1
        image: node:16-alpine
        # Lệnh sẽ được chạy trong container
        command: sh -c "yarn install && yarn run dev"
        # Detach port
        ports:
            - 3000:3000
        # Thiết lập thư mục làm việc
        # Các commands sẽ được chạy ở thư mục này
        working_dir: /app 
        # Bind mount thư mục hiện tại (.) từ máy host với thư mục app trong container
        volumes:
            - ./:/app
        # Thiết lặp các biến môi trường để kết nối với MySQL
        environment:
            # Tên của container MySQL
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: todos
        # Khai báo network
        networks:
            - todo-app-default
    # Container 2
    mysql:
        # Image dùng để build container 2
        image: mysql:5.7
        # Sử dụng volume todo-mysql-data
        # Thư mục trên máy host sẽ được lưu trữ dữ liệu: /var/lib/mysql
        volumes:
            - todo-mysql-data:/var/lib/mysql
        # Thiết lập các biến môi trường cho MySQL
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todos
        # Khai báo network
        networks:
            - todo-app-default
volumes:
    todo-mysql-data:
networks:
    todo-app-default: